### ISSUE TITLE
BurpKit window empty

### ISSUE THREAD

**Issue by schniggie** [allfro/BurpKit#1]
Hey,

I just installed the pre release 1.0 of BurpKit. Using Burp 1.6.24 and Java 8 (java version "1.8.0_51").
I don't see any errors in the Extender tab.

Any way howto debug this easily?

**Comment by allfro** [comment]
Hi @schniggie

What OS platform are you running this on? Also, could you attach a screenshot? Finally, try running Burp from the command line using `java -jar burpsuite_1.6.22.jar` and you may see an exception message in the console.

**Comment by hellasecure** [comment]
I am having a similar issue. When I run burp from command line then enable the extension, I get the following stack trace: http://pastebin.com/zt1wvi9H

**Comment by allfro** [comment]
Hi all

Which distribution are you using? The one in the releases page, the github
repo, or on the DEFCON server?

**Comment by hellasecure** [comment]
I got the jar file from the release page.

**Comment by hellasecure** [comment]
I figured it out. I needed to wipe out my entire installation of Java in my VM and reinstall, then it worked. Great plugin, thanks!

**Comment by schniggie** [comment]
@allfro I'm using Kali 1.1.0c and when using java -jar burp.jar there is none exception in the console.
![burpkit01](https://cloud.githubusercontent.com/assets/637619/9191217/c06c20e2-3ffe-11e5-8b7d-aad90d10248a.png)

**Comment by allfro** [comment]
@schniggie could you please give me the output of `java -version`

**Comment by schniggie** [comment]
@allfro
root@kali:~/offsec/burp# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by allfro** [comment]
@schniggie which JAR file did you use?

**Comment by schniggie** [comment]
@allfro BurpKit v1.0-pre

**Comment by allfro** [comment]
@schniggie try this one: https://media.defcon.org/DEF%20CON%2023/DEF%20CON%2023%20presentations/Speaker%20&%20Workshop%20Materials/Nadeem%20Douba/Extras/BurpKit.jar

**Comment by schniggie** [comment]
Nope same problem, also changed extension options to output error to console instead of ui but no error or exception appears

**Comment by allfro** [comment]
@schniggie would you be open to a live troubleshooting session using something like TeamView?

**Comment by schniggie** [comment]
@allfro Sure. When do you have time :)? Got a phone conference and I'm free in 30 minutes. how can I contact you?

**Comment by allfro** [comment]
@schniggie unfortunately it is 3am right now. Can we do this tomorrow? What time works for you? I can be reached on skype nadeem.douba

**Comment by schniggie** [comment]
@allfro ok here it's 10.30am right now, so i think about 5h difference. I added you on skpye. thanks in advance

**Comment by allfro** [comment]
Hi schniggie, are you free today? I am on Skype atm.

**Comment by hasasn** [comment]
@melanko fix worked for me as well.

**Comment by allfro** [comment]
Hi all,

What operating system are you using this on?

**Comment by allfro** [comment]
See latest release and commits for fix (https://github.com/allfro/BurpKit/releases/tag/v1.01-pre)
