### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by manuelbua** [allfro/BurpKit#11]
I'm running BurpKit 1.03-PRE on Kali 2 / BurpSuite Pro 1.7.12 (pro) and i keep getting this error as soon as i load the extension.
I can see it could happen if the extract `.so` library in the `temp` directory didn't have execution rights, but it looks like its all fine there:

```
-rwxr--r--  1 root       root       769216 Nov 19 23:49 sqlite-3.8.10.1-3d07f89e-bfd2-44e8-9ade-e8ec95e626d2-libsqlitejdbc.so
-rwxr--r--  1 root       root       769216 Nov 19 23:52 sqlite-3.8.10.1-97958006-59e5-4c2e-aad8-00a8821aba40-libsqlitejdbc.so
-rwxr--r--  1 root       root       769216 Nov 19 23:54 sqlite-3.8.10.1-9c1582f4-aee8-43b4-ba22-e6ad4917df00-libsqlitejdbc.so
-rwxr--r--  1 root       root       769216 Nov 19 23:51 sqlite-3.8.10.1-af12e2c3-b87f-4dbb-a44e-2c5f80261fe4-libsqlitejdbc.so
-rwxr--r--  1 root       root       769216 Nov 19 23:35 sqlite-3.8.10.1-e10c92ce-4477-4e66-9fd5-16d92100f21b-libsqlitejdbc.so
```

I also tried to set the additional Java Envrionment directory that Burp can use for Java extensions to no avail, did this ever happen to someone else?

**Comment by allfro** [comment]
You probably have to install sqlite3-dev or libsqlite3-dev. Not sure which
one it is in Kali

**Comment by manuelbua** [comment]
Thanks for getting back to me so fast!
I ithought so, but i had that installed already: i'm now looking at the console error that couldn't see in the UI, so i'm searching for references about this:

```
Warning: context class loader for JFX thread returned null.
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.8.10.1-c0f0b6d8-4917-4d30-aca5-0828606fb901-libsqlitejdbc.so: /tmp/sqlite-3.8.10.1-c0f0b6d8-4917-4d30-aca5-0828606fb901-libsqlitejdbc.so: failed to map segment from shared object
```

The first warning looks like it's related to the UI, but the more specific error on the library is interesting.

**Comment by allfro** [comment]
Perhaps not enough ram allocated to the JVM?

**Comment by manuelbua** [comment]
That may be possible, i also found out my `/tmp` partition is mounted as **noexec**:
`tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,noatime,size=2097152k)`

I'm going to try raise the memory first, let's see if it's that.

**Comment by manuelbua** [comment]
I tried running with `-Xmn2048M -Xms2048M -Xmx4096M` and nothing changes: now trying to remount without the `noexec` with `mount -o remount,exec /tmp`.

**Comment by manuelbua** [comment]
Great, it's working fine now! I can finally take a look at this game-changing extension, thanks for all the hard work you put into it!

**Comment by allfro** [comment]
Glad to hear it worked out! enjoy!
