### ISSUE TITLE
Upstream Proxy Support

### ISSUE THREAD

**Issue by hasasn** [allfro/BurpKit#2]
Currently use BurpSuite behind an upstream proxy pac.

proxy.xxxxxxx.com:80 

Unknown Host error pops up for any navigation items in BurpKit. Proxy disabled everything works great. 
![screen shot 2015-08-12 at 1 18 40 pm](https://cloud.githubusercontent.com/assets/6047192/9235629/b79d3dce-40f4-11e5-812f-8b5bc6f4aad9.png)

Java: 1.8.0_51
Burp: 1.6.24
Mac: 10.10.4

**Comment by allfro** [comment]
Is that upstream proxy setting being set in the OS or in BurpSuite?

**Comment by hasasn** [comment]
Set directly in BurpSuite.

Options => Upstream Proxy Servers => Enabled [PROXY INFO]
No authentication.

**Comment by SecMyth** [comment]
I'm having the same issue. BurpKit seems to ignore the proxy settings of Burp. In my opinion it should stick to the Burp proxy settings and not to the OS one.
Please support proxies.

**Comment by allfro** [comment]
I will look into what the issue is as soon as we solve the blank screen
issue for other users. If any of you have solved this issue a solution with
detailed steps would be greatly appreciated :)

**Comment by allfro** [comment]
Looking into this now. Any reproduction steps would be greatly appreciated as I am unable to reproduce the issue on my end. I have set the upstream proxy setting but it has no effect on BurpKit. BurpKit appears to be operating normally?

**Comment by allfro** [comment]
There is now support for upstream proxying with the added feature of a proxy toggle button in the toolbar. This will push requests through the burpsuite proxy when enabled and thus take advantage of the upstream proxy settings in burp. The only downside is that your requests will show up in your proxy history.
