### ISSUE TITLE
Setting proxy for BurpKitty?

### ISSUE THREAD

**Issue by hvqzao** [allfro/BurpKit#7]
Right now (v1.01-pre) BurpKitty does not use any proxy setting.
I don't see any option to configure such, also explicit proxy configuration in IE, Java and then restarting Burp does not seem to have any effect.
I'd like to set BurpKitty to go through Burp proxy.
Did you consider adding proxy settings i.e. as a button next to "take screenshot"?

**Comment by allfro** [comment]
There is now a proxy button next to the screen shot button. When toggled it pushes requests through BurpSuite proxy. You can take advantage of the upstream proxy settings to push it through your custom proxy.
